syntax on
set spell 
set omnifunc=syntaxcomplete#Complete
set linebreak
set relativenumber
set number
set ruler
set cursorline
set background=dark
set autoindent
set expandtab
set shiftwidth=4
set tabstop=4
set encoding=utf-8
set fileencoding=utf-8
set dictionary=/usr/share/dict/words
set thesaurus=/Users/quindarius/Documents/books/thesaurus.txt 
set spellfile=/Users/quindarius/.vim/spell/en.utf-8.add
